spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/secondhand
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088

cloudinary.cloud-name=dey3hyep9
cloudinary.api-key=331694698623197
cloudinary.api-secret=J29l7WhqAptQ2Pu9_VLE50yDuKs